//! L4 — render the computed knowledge graph (communities + god-nodes + members)
//! into the `KNOWLEDGE_GRAPH.md` markdown the agent reads to orient.
//!
//! Pure (no I/O), so it is unit-testable. The caller (graph_file.rs) supplies
//! already-computed communities; this only formats. Keep it compact — it is
//! payload the agent pays tokens for (see ticket success criterion).

/// One topic cluster for the digest.
#[derive(Debug, Clone)]
pub struct CommunityView {
    /// God-node entity names (highest-degree, hub-excluded) — the concepts the
    /// cluster is "about". Ordered most→least central.
    pub god_entities: Vec<String>,
    /// Representative member file paths (a sample, not necessarily all).
    pub member_files: Vec<String>,
    /// Total members in the cluster (member_files may be truncated).
    pub size: usize,
}

/// Render the full `KNOWLEDGE_GRAPH.md`. `dir_map` = (top-level dir, file count),
/// already sorted. `total_files` = indexed files. Communities are expected
/// largest-first. `max_files_per_topic` bounds the per-topic sample.
pub fn render(
    communities: &[CommunityView],
    total_files: usize,
    dir_map: &[(String, usize)],
    max_files_per_topic: usize,
) -> String {
    let mut s = String::new();
    s.push_str("# KNOWLEDGE_GRAPH.md — workspace knowledge graph (auto-generated by semfs)\n\n");
    s.push_str(
        "This mount is a dynamic semantic index. This file is the whole-workspace knowledge \
         graph: topic clusters (communities) labeled by their central entities (god-nodes), \
         plus the directory map. It updates as files are added/removed.\n\n",
    );
    s.push_str(
        "How to use: read this to orient, then run `semfs grep \"2-4 key terms\"` for ranked \
         excerpts. Query in the corpus's own language for best recall.\n\n",
    );

    let topics = communities
        .iter()
        .filter(|c| !c.god_entities.is_empty())
        .count();
    s.push_str(&format!(
        "## Topics — {topics} clusters across {total_files} files\n",
    ));
    if communities.iter().all(|c| c.god_entities.is_empty()) {
        s.push_str("_(entity graph still sparse — run more L7 extraction for richer topics)_\n");
    }
    for c in communities {
        if c.god_entities.is_empty() {
            continue;
        }
        let label = c.god_entities.join(", ");
        s.push_str(&format!("\n★ {label}  — {} file(s)\n", c.size));
        for f in c.member_files.iter().take(max_files_per_topic) {
            s.push_str(&format!("   - {f}\n"));
        }
        if c.size > max_files_per_topic {
            s.push_str(&format!("   … +{} more\n", c.size - max_files_per_topic));
        }
    }

    s.push_str("\n## Directory map\n");
    for (dir, n) in dir_map {
        s.push_str(&format!("   {dir}  ({n} file(s))\n"));
    }
    s.push_str("\n_(semfs: `grep` searches by meaning; this graph is for orientation.)_\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_topics_and_dirmap() {
        let coms = vec![
            CommunityView {
                god_entities: vec!["畅销产品".into(), "成交金额".into()],
                member_files: vec!["/desktop/a.txt".into(), "/desktop/b.txt".into()],
                size: 5,
            },
            CommunityView {
                god_entities: vec!["taobao".into()],
                member_files: vec!["/taobao/x.xlsx".into()],
                size: 1,
            },
        ];
        let dirs = vec![("/desktop".to_string(), 5), ("/taobao".to_string(), 1)];
        let md = render(&coms, 6, &dirs, 3);
        assert!(md.contains("KNOWLEDGE_GRAPH.md"));
        assert!(md.contains("★ 畅销产品, 成交金额  — 5 file(s)"));
        assert!(md.contains("/desktop/a.txt"));
        assert!(md.contains("## Directory map"));
        assert!(md.contains("/taobao  (1 file(s))"));
        assert!(md.contains("semfs grep"));
    }

    #[test]
    fn truncates_member_sample() {
        let coms = vec![CommunityView {
            god_entities: vec!["X".into()],
            member_files: (0..10).map(|i| format!("/f{i}.txt")).collect(),
            size: 10,
        }];
        let md = render(&coms, 10, &[], 3);
        assert!(md.contains("/f0.txt"));
        assert!(md.contains("/f2.txt"));
        assert!(!md.contains("/f3.txt")); // capped at 3
        assert!(md.contains("… +7 more"));
    }

    #[test]
    fn empty_graph_notes_sparsity() {
        let coms = vec![CommunityView {
            god_entities: vec![],
            member_files: vec!["/a".into()],
            size: 1,
        }];
        let md = render(&coms, 1, &[("/".into(), 1)], 3);
        assert!(md.contains("entity graph still sparse"));
    }
}
